from dataclasses import dataclass

from app.orchestrator import WorkflowTask


@dataclass
class ScenarioDefinition:
    name: str
    requirement: str
    assumptions: list[str]
    risks: list[str]
    validation_steps: list[str]
    tasks: dict[str, WorkflowTask]


def build_greenfield_scenario() -> ScenarioDefinition:
    tasks = {
        "requirement_analysis": WorkflowTask(
            name="requirement_analysis",
        ),
        "architecture_design": WorkflowTask(
            name="architecture_design",
            dependencies=["requirement_analysis"],
        ),
        "security_review": WorkflowTask(
            name="security_review",
            dependencies=["requirement_analysis"],
        ),
        "implementation": WorkflowTask(
            name="implementation",
            dependencies=[
                "architecture_design",
                "security_review",
            ],
            requires_approval=True,
        ),
        "testing": WorkflowTask(
            name="testing",
            dependencies=["implementation"],
        ),
        "documentation": WorkflowTask(
            name="documentation",
            dependencies=["implementation"],
        ),
        "release_review": WorkflowTask(
            name="release_review",
            dependencies=[
                "testing",
                "documentation",
            ],
            requires_approval=True,
        ),
    }

    return ScenarioDefinition(
        name="greenfield",
        requirement=(
            "Build a new production-style URL shortener "
            "with redirect and click analytics."
        ),
        assumptions=[
            "Python and FastAPI are acceptable technologies.",
            "SQLite is acceptable for the prototype.",
            "Short codes are generated by the service.",
        ],
        risks=[
            "Short-code collisions.",
            "Invalid URLs.",
            "Database persistence failures.",
            "Unsafe autonomous release decisions.",
        ],
        validation_steps=[
            "Validate incoming URLs.",
            "Test unique short-code creation.",
            "Test redirect behavior.",
            "Verify analytics increments.",
            "Require approval before implementation and release.",
        ],
        tasks=tasks,
    )


def build_brownfield_scenario() -> ScenarioDefinition:
    tasks = {
        "change_request_analysis": WorkflowTask(
            name="change_request_analysis",
        ),
        "impact_analysis": WorkflowTask(
            name="impact_analysis",
            dependencies=["change_request_analysis"],
        ),
        "data_model_review": WorkflowTask(
            name="data_model_review",
            dependencies=["change_request_analysis"],
        ),
        "implementation": WorkflowTask(
            name="implementation",
            dependencies=[
                "impact_analysis",
                "data_model_review",
            ],
            requires_approval=True,
        ),
        "regression_testing": WorkflowTask(
            name="regression_testing",
            dependencies=["implementation"],
        ),
        "migration_validation": WorkflowTask(
            name="migration_validation",
            dependencies=["implementation"],
        ),
        "release_review": WorkflowTask(
            name="release_review",
            dependencies=[
                "regression_testing",
                "migration_validation",
            ],
            requires_approval=True,
        ),
    }

    return ScenarioDefinition(
        name="brownfield",
        requirement=(
            "Enhance the existing URL shortener so links "
            "can optionally expire."
        ),
        assumptions=[
            "Existing URL behavior must remain backward compatible.",
            "Existing links without expiration continue to work.",
            "Expiration is optional.",
        ],
        risks=[
            "Breaking existing links.",
            "Incorrect database migration.",
            "Timezone handling errors.",
            "Regression in redirect behavior.",
        ],
        validation_steps=[
            "Identify impacted API and database modules.",
            "Test existing non-expiring links.",
            "Test expired links.",
            "Test active links with future expiration.",
            "Validate database migration behavior.",
        ],
        tasks=tasks,
    )


def build_ambiguous_scenario() -> ScenarioDefinition:
    tasks = {
        "requirement_interpretation": WorkflowTask(
            name="requirement_interpretation",
        ),
        "ambiguity_detection": WorkflowTask(
            name="ambiguity_detection",
            dependencies=["requirement_interpretation"],
        ),
        "human_clarification": WorkflowTask(
            name="human_clarification",
            dependencies=["ambiguity_detection"],
            requires_approval=True,
        ),
        "solution_design": WorkflowTask(
            name="solution_design",
            dependencies=["human_clarification"],
        ),
        "implementation": WorkflowTask(
            name="implementation",
            dependencies=["solution_design"],
            requires_approval=True,
        ),
        "security_validation": WorkflowTask(
            name="security_validation",
            dependencies=["implementation"],
        ),
        "release_review": WorkflowTask(
            name="release_review",
            dependencies=["security_validation"],
            requires_approval=True,
        ),
    }

    return ScenarioDefinition(
        name="ambiguous",
        requirement=(
            "Make shortened links more secure."
        ),
        assumptions=[
            "The phrase 'more secure' is not sufficiently specific.",
            "The system should not autonomously choose a "
            "high-impact interpretation.",
        ],
        risks=[
            "Implementing the wrong security control.",
            "Changing expected link behavior.",
            "Over-restricting legitimate redirects.",
            "Proceeding without stakeholder clarification.",
        ],
        validation_steps=[
            "Detect ambiguity before implementation.",
            "Pause for human clarification.",
            "Record the approved interpretation.",
            "Run security-focused validation.",
            "Require release approval.",
        ],
        tasks=tasks,
    )